[2019-02-03 11:10:40 +0800] [148] [DEBUG] Current configuration:
  config: gunicorn.py
  bind: ['0.0.0.0:5000']
  backlog: 2048
  workers: 13
  worker_class: gevent
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 60
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /code
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: ./logs/gunicorn/falsk_app-acess-2019-02-03.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: ./logs/gunicorn/falsk_app-error-2019-02-03.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  statsd_prefix: 
  proc_name: None
  default_proc_name: auto_app:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f88d5a89378>
  on_reload: <function OnReload.on_reload at 0x7f88d5a89488>
  when_ready: <function WhenReady.when_ready at 0x7f88d5a89598>
  pre_fork: <function Prefork.pre_fork at 0x7f88d5a896a8>
  post_fork: <function Postfork.post_fork at 0x7f88d5a897b8>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f88d5a898c8>
  worker_int: <function WorkerInt.worker_int at 0x7f88d5a899d8>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f88d5a89ae8>
  pre_exec: <function PreExec.pre_exec at 0x7f88d5a89bf8>
  pre_request: <function PreRequest.pre_request at 0x7f88d5a89d08>
  post_request: <function PostRequest.post_request at 0x7f88d5a89d90>
  child_exit: <function ChildExit.child_exit at 0x7f88d5a89ea0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f88d5a9f048>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f88d5a9f158>
  on_exit: <function OnExit.on_exit at 0x7f88d5a9f268>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: TLSv1
  raw_paste_global_conf: []
[2019-02-03 11:10:40 +0800] [148] [INFO] Starting gunicorn 19.9.0
[2019-02-03 11:10:40 +0800] [148] [DEBUG] Arbiter booted
[2019-02-03 11:10:40 +0800] [148] [INFO] Listening at: http://0.0.0.0:5000 (148)
[2019-02-03 11:10:40 +0800] [148] [INFO] Using worker: gevent
[2019-02-03 11:10:40 +0800] [151] [INFO] Booting worker with pid: 151
[2019-02-03 11:10:40 +0800] [152] [INFO] Booting worker with pid: 152
[2019-02-03 11:10:40 +0800] [153] [INFO] Booting worker with pid: 153
[2019-02-03 11:10:40 +0800] [154] [INFO] Booting worker with pid: 154
[2019-02-03 11:10:40 +0800] [155] [INFO] Booting worker with pid: 155
[2019-02-03 11:10:40 +0800] [157] [INFO] Booting worker with pid: 157
[2019-02-03 11:10:40 +0800] [156] [INFO] Booting worker with pid: 156
[2019-02-03 11:10:40 +0800] [158] [INFO] Booting worker with pid: 158
[2019-02-03 11:10:40 +0800] [161] [INFO] Booting worker with pid: 161
[2019-02-03 11:10:40 +0800] [162] [INFO] Booting worker with pid: 162
[2019-02-03 11:10:40 +0800] [165] [INFO] Booting worker with pid: 165
[2019-02-03 11:10:40 +0800] [166] [INFO] Booting worker with pid: 166
[2019-02-03 11:10:40 +0800] [168] [INFO] Booting worker with pid: 168
[2019-02-03 11:10:40 +0800] [148] [DEBUG] 13 workers
[2019-02-03 11:11:14 +0800] [161] [DEBUG] GET /index/
[2019-02-03 11:11:14 +0800] [161] [DEBUG] POST /api/post/getPostList
[2019-02-03 11:11:14 +0800] [162] [DEBUG] POST /api/post/getTag
[2019-02-03 11:11:14 +0800] [162] [DEBUG] GET /_debug_toolbar/static/css/toolbar.css
[2019-02-03 11:11:14 +0800] [161] [ERROR] Error handling request /api/post/getPostList
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 493, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 550, in _connect
    raise err
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 538, in _connect
    sock.connect(socket_address)
  File "/usr/local/lib/python3.6/site-packages/gevent/_socket3.py", line 356, in connect
    raise error(result, strerror(result))
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/walrus/database.py", line 118, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 594, in send_packed_command
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 498, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 493, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 550, in _connect
    raise err
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 538, in _connect
    sock.connect(socket_address)
  File "/usr/local/lib/python3.6/site-packages/gevent/_socket3.py", line 356, in connect
    raise error(result, strerror(result))
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
    addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/code/api_views/base/api.py", line 28, in dispatch_request
    return api_method()
  File "/code/api_views/post_api.py", line 43, in getPostList
    res = Post.get_posts_list(page, limit, order_by)
  File "/code/base/mc.py", line 100, in _
    r = rdb.get(key) if not force else None
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 1207, in get
    return self.execute_command('GET', name)
  File "/usr/local/lib/python3.6/site-packages/walrus/database.py", line 125, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 594, in send_packed_command
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 498, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address.
[2019-02-03 11:11:14 +0800] [162] [DEBUG] GET /static/ele_ui_web/favicon.ico
[2019-02-03 11:11:19 +0800] [157] [DEBUG] GET /static/ele_ui_web/static/js/manifest.c582ee93643d7c50d417.js.map
[2019-02-03 11:11:19 +0800] [166] [DEBUG] GET /static/ele_ui_web/static/js/app.9116e98aa994e2b5edde.js.map
[2019-02-03 11:11:19 +0800] [168] [DEBUG] GET /static/ele_ui_web/static/css/app.ec55e1543cb9e0de8f55453c106d7e4e.css.map
[2019-02-03 11:11:19 +0800] [166] [DEBUG] GET /static/ele_ui_web/static/js/vendor.d9f8435f7a13d4255019.js.map
[2019-02-03 11:57:15 +0800] [148] [INFO] Handling signal: int
[2019-02-03 11:57:15 +0800] [153] [INFO] Worker exiting (pid: 153)
[2019-02-03 11:57:15 +0800] [151] [INFO] Worker exiting (pid: 151)
[2019-02-03 11:57:15 +0800] [154] [INFO] Worker exiting (pid: 154)
[2019-02-03 11:57:15 +0800] [157] [INFO] Worker exiting (pid: 157)
[2019-02-03 11:57:15 +0800] [162] [INFO] Worker exiting (pid: 162)
[2019-02-03 11:57:15 +0800] [161] [INFO] Worker exiting (pid: 161)
[2019-02-03 11:57:15 +0800] [166] [INFO] Worker exiting (pid: 166)
[2019-02-03 11:57:15 +0800] [165] [INFO] Worker exiting (pid: 165)
[2019-02-03 11:57:15 +0800] [152] [INFO] Worker exiting (pid: 152)
[2019-02-03 11:57:15 +0800] [158] [INFO] Worker exiting (pid: 158)
[2019-02-03 11:57:15 +0800] [155] [INFO] Worker exiting (pid: 155)
[2019-02-03 11:57:15 +0800] [156] [INFO] Worker exiting (pid: 156)
[2019-02-03 11:57:15 +0800] [168] [INFO] Worker exiting (pid: 168)
[2019-02-03 11:57:16 +0800] [148] [INFO] Shutting down: Master
